### ISSUE TITLE
The example colors.cr did not show anything on the terminal

### ISSUE THREAD

**Issue by evandrojr** [agatan/ncurses.cr#2]
I tried that:

crystal run example/colors.cr

and nothing happens at all!

Using Ubuntu 16.04 crystal 0.24.2

Please, add this to your readme:
https://stackoverflow.com/questions/26186824/how-to-install-the-ncursesw-development-libraries

**Comment by agatan** [comment]
Thanks for your feedback.
I just added ncurses installation instructions to README.md.
